import {SalesOffer} from '@/screens';

const Images = {
  // PNG Icons
  Dashbboard: require('@/assets/icons/dashboard.png'),
  Leads: require('@/assets/icons/leads.png'),
  Menu: require('@/assets/icons/menu.png'),
  SalesOffer: require('@/assets/icons/salesOffer.png'),
  EOI: require('@/assets/icons/EOI.png'),
  Commission: require('@/assets/icons/commission.png'),
  User: require('@/assets/icons/user.png'),
  Arrow: require('@/assets/icons/arrow.png'),
  DummyFlag: require('@/assets/icons/flagIcon.png'),
  ArrowChevron: require('@/assets/icons/arrow-chevron.png'),
  RightArrow: require('@/assets/icons/arrow-right.png'),
  Exclamination: require('@/assets/icons/exclamination.png'),
  Tick: require('@/assets/icons/tick.png'),
  BlackCross: require('@/assets/icons/cross-dark.png'),
  Cross: require('@/assets/icons/cross.png'),
  // EyeInactive: require('@/assets/icons/eye_disable.png'),
  FaceId: require('@/assets/icons/faceid.png'),
  Success: require('@/assets/icons/success.png'),
  Calendar: require('@/assets/icons/calendar.png'),
  GreenShield: require('@/assets/icons/green-shield.png'),
  avatar: require('@/assets/icons/avatar.png'),
  Search: require('@/assets/icons/search.png'),
  Add: require('@/assets/icons/add.png'),
  Location: require('@/assets/icons/location.png'),
  Phone: require('@/assets/icons/phone.png'),
  Document: require('@/assets/icons/document.png'),
  Beyond: require('@/assets/icons/beyond.png'),
  UAE: require('@/assets/icons/uae.png'),
  EmptyIcon: require('../../assets/icons/emptyIcon.png'),
  Delete: require('@/assets/icons/delete.png'),
  Plus: require('@/assets/icons/plus.png'),
  YellowShield: require('@/assets/icons/yellow-shield.png'),
  Download: require('@/assets/icons/download.png'),
  // Images
  Registeration_1: require('@/assets/images/registeration-1.jpg'),
  Registeration_2: require('@/assets/images/registeration-2.jpg'),
  LoginBackground: require('@/assets/images/login-bg.png'),
  AuthBackground: require('@/assets/images/auth-bg.png'),
  // SVG Icons
  SalesOfferSVG: require('@/assets/svg/salesOffer.svg').default,
  CommissionSVG: require('@/assets/svg/commission.svg').default,
  EoiSVG: require('@/assets/svg/EOI.svg').default,
  HelpSVG: require('@/assets/svg/help.svg').default,
  UserSVG: require('@/assets/svg/user.svg').default,
  LeadsSVG: require('@/assets/svg/leads.svg').default,
  DashboardSVG: require('@/assets/svg/dashboard.svg').default,
  LogoutSVG: require('@/assets/svg/logout.svg').default,
  MenuSVG: require('@/assets/svg/menu.svg').default,
  NotificationSVG: require('@/assets/svg/notification.svg').default,
  UserPlaceholderSVG: require('@/assets/svg/userPlaceHolder.svg').default,
  RefreshSVG: require('@/assets/svg/refresh.svg').default,
  UnitsSoldSVG: require('@/assets/svg/unitSold.svg').default,
  CustomerSVG: require('@/assets/svg/customers.svg').default,
  SoldValueSVG: require('@/assets/svg/soldvalue.svg').default,
  CommissionDashboardSVG: require('@/assets/svg/commissiondashboard.svg')
    .default,
  SendSVG: require('@/assets/svg/send.svg').default,
  DownloadSVG: require('@/assets/svg/download.svg').default,
  WhatsappSVG: require('@/assets/svg/whatsapp.svg').default,
  EmailSVG: require('@/assets/svg/email.svg').default,
  FullArrowSVG: require('@/assets/svg/full-arrow.svg').default,
  FaceIdSVG: require('@/assets/svg/faceid.svg').default,
  BagSVG: require('@/assets/svg/bag.svg').default,
  EyeInactiveSVG: require('@/assets/svg/eyeHide.svg').default,
  EyeActiveSVG: require('@/assets/svg/eyeopen.svg').default,
  PasswordSVG: require('@/assets/svg/lock.svg').default,
  UploadSVG: require('@/assets/svg/upload.svg').default,
  CheckSVG: require('@/assets/svg/check.svg').default,
  AvatarSVG: require('@/assets/svg/avatar.svg').default,
  EmptyIconSVG: require('@/assets/svg/emptyIcon.svg').default,
};

export default Images;
