import i18next from 'i18next';
import {Platform} from 'react-native';
import DeviceInfo from 'react-native-device-info';

export const PAGE_SIZE = 10;
export const OTP_DIGITS = 4;
export const ACTIVE_OPACITY = 0.9;
export const EXTRA_SCROLL_HEIGHT = Platform.select({
  ios: -100,
  android: 10,
});
export const BROKER_FEATURES = [
  'Manage client interest submissions.',
  'Commission details',
  'Manage offers for potential sales.',
  'Introduce leads',
  'Edit your profile and settings.',
  'Full transparency at every step.',
];
export const PASSWORD_REQUIREMENTS = [
  'Must be more than 8 characters long',
  'Should contain at least 1 uppercase character',
  'Should contain at least 1 lowercase character',
  'Should contain at least 1 numeric character',
  'Should contain at least 1 special character',
];
export const LANG_EN = 'en';
export const LANG_AR = 'ar';
export const SELECTED_LANG = i18next.language == LANG_AR;
export const readableVersion = DeviceInfo.getReadableVersion();
export const monnthsList = [
  'Jan',
  'Feb',
  'Mar',
  'Apr',
  'May',
  'Jun',
  'Jul',
  'Aug',
  'Sep',
  'Oct',
  'Nov',
  'Dec',
];

export const countryCodes = [
  {country: 'Afghanistan', code: '93'},
  {country: 'Åland Islands', code: '358'},
  {country: 'Albania', code: '355'},
  {country: 'Algeria', code: '213'},
  {country: 'American Samoa', code: '1684'},
  {country: 'Andorra', code: '376'},
  {country: 'Angola', code: '244'},
  {country: 'Anguilla', code: '1264'},
  {country: 'Antarctica', code: '672'},
  {country: 'Antigua and Barbuda', code: '1268'},
  {country: 'Argentina', code: '54'},
  {country: 'Armenia', code: '374'},
  {country: 'Aruba', code: '297'},
  {country: 'Australia', code: '61'},
  {country: 'Austria', code: '43'},
  {country: 'Azerbaijan', code: '994'},
  {country: 'Bahamas', code: '1242'},
  {country: 'Bahrain', code: '973'},
  {country: 'Bangladesh', code: '880'},
  {country: 'Barbados', code: '1246'},
  {country: 'Belarus', code: '375'},
  {country: 'Belgium', code: '32'},
  {country: 'Belize', code: '501'},
  {country: 'Benin', code: '229'},
  {country: 'Bermuda', code: '1441'},
  {country: 'Bhutan', code: '975'},
  {country: 'Bolivia', code: '591'},
  {country: 'Bonaire', code: '599'},
  {country: 'Bosnia and Herzegovina', code: '387'},
  {country: 'Botswana', code: '267'},
  {country: 'Brazil', code: '55'},
  {country: 'British Indian Ocean Territory', code: '246'},
  {country: 'British Virgin Islands', code: '1284'},
  {country: 'Brunei', code: '673'},
  {country: 'Bulgaria', code: '359'},
  {country: 'Burkina Faso', code: '226'},
  {country: 'Burundi', code: '257'},
  {country: 'Cabo Verde', code: '238'},
  {country: 'Cambodia', code: '855'},
  {country: 'Cameroon', code: '237'},
  {country: 'Canada', code: '1'},
  {country: 'Cayman Islands', code: '1345'},
  {country: 'Central African Republic', code: '236'},
  {country: 'Chad', code: '235'},
  {country: 'Chile', code: '56'},
  {country: 'China', code: '86'},
  {country: 'Christmas Island', code: '61'},
  {country: 'Cocos', code: '61'},
  {country: 'Colombia', code: '57'},
  {country: 'Comoros', code: '269'},
  {country: 'Congo', code: '242'},
  {country: 'Congo (DRC)', code: '243'},
  {country: 'Cook Islands', code: '682'},
  {country: 'Costa Rica', code: '506'},
  {country: 'Côte d’Ivoire', code: '225'},
  {country: 'Croatia', code: '385'},
  {country: 'Cuba', code: '53'},
  {country: 'Curaçao', code: '599'},
  {country: 'Cyprus', code: '357'},
  {country: 'Czech Republic', code: '420'},
  {country: 'Denmark', code: '45'},
  {country: 'Djibouti', code: '253'},
  {country: 'Dominica', code: '1767'},
  {country: 'Dominican Republic', code: '849'},
  {country: 'Ecuador', code: '593'},
  {country: 'Egypt', code: '20'},
  {country: 'El Salvador', code: '503'},
  {country: 'Equatorial Guinea', code: '240'},
  {country: 'Eritrea', code: '291'},
  {country: 'Estonia', code: '372'},
  {country: 'Eswatini', code: '268'},
  {country: 'Ethiopia', code: '251'},
  {country: 'Falkland Islands', code: '500'},
  {country: 'Faroe Islands', code: '298'},
  {country: 'Fiji', code: '679'},
  {country: 'Finland', code: '358'},
  {country: 'France', code: '33'},
  {country: 'French Guiana', code: '594'},
  {country: 'French Polynesia', code: '689'},
  {country: 'Gabon', code: '241'},
  {country: 'Gambia', code: '220'},
  {country: 'Georgia', code: '995'},
  {country: 'Germany', code: '49'},
  {country: 'Ghana', code: '233'},
  {country: 'Gibraltar', code: '350'},
  {country: 'Greece', code: '30'},
  {country: 'Greenland', code: '299'},
  {country: 'Grenada', code: '1473'},
  {country: 'Guadeloupe', code: '590'},
  {country: 'Guam', code: '1671'},
  {country: 'Guatemala', code: '502'},
  {country: 'Guernsey', code: '44'},
  {country: 'Guinea', code: '224'},
  {country: 'Guinea-Bissau', code: '245'},
  {country: 'Guyana', code: '592'},
  {country: 'Haiti', code: '509'},
  {country: 'Honduras', code: '504'},
  {country: 'Hong Kong', code: '852'},
  {country: 'Hungary', code: '36'},
  {country: 'Iceland', code: '354'},
  {country: 'India', code: '91'},
  {country: 'Indonesia', code: '62'},
  {country: 'Iran', code: '98'},
  {country: 'Iraq', code: '964'},
  {country: 'Ireland', code: '353'},
  {country: 'Isle of Man', code: '44'},
  {country: 'Israel', code: '972'},
  {country: 'Italy', code: '39'},
  {country: 'Jamaica', code: '1876'},
  {country: 'Japan', code: '81'},
  {country: 'Jersey', code: '44'},
  {country: 'Jordan', code: '962'},
  {country: 'Kazakhstan', code: '7'},
  {country: 'Kenya', code: '254'},
  {country: 'Kiribati', code: '686'},
  {country: 'Kuwait', code: '965'},
  {country: 'Kyrgyzstan', code: '996'},
  {country: 'Laos', code: '856'},
  {country: 'Latvia', code: '371'},
  {country: 'Lebanon', code: '961'},
  {country: 'Lesotho', code: '266'},
  {country: 'Liberia', code: '231'},
  {country: 'Libya', code: '218'},
  {country: 'Liechtenstein', code: '423'},
  {country: 'Lithuania', code: '370'},
  {country: 'Luxembourg', code: '352'},
  {country: 'Macau', code: '853'},
  {country: 'Madagascar', code: '261'},
  {country: 'Malawi', code: '265'},
  {country: 'Malaysia', code: '60'},
  {country: 'Maldives', code: '960'},
  {country: 'Mali', code: '223'},
  {country: 'Malta', code: '356'},
  {country: 'Marshall Islands', code: '692'},
  {country: 'Martinique', code: '596'},
  {country: 'Mauritania', code: '222'},
  {country: 'Mauritius', code: '230'},
  {country: 'Mayotte', code: '262'},
  {country: 'Mexico', code: '52'},
  {country: 'Micronesia', code: '691'},
  {country: 'Moldova', code: '373'},
  {country: 'Monaco', code: '377'},
  {country: 'Mongolia', code: '976'},
  {country: 'Montenegro', code: '382'},
  {country: 'Montserrat', code: '1664'},
  {country: 'Morocco', code: '212'},
  {country: 'Mozambique', code: '258'},
  {country: 'Myanmar', code: '95'},
  {country: 'Namibia', code: '264'},
  {country: 'Nauru', code: '674'},
  {country: 'Nepal', code: '977'},
  {country: 'Netherlands', code: '31'},
  {country: 'New Caledonia', code: '687'},
  {country: 'New Zealand', code: '64'},
  {country: 'Nicaragua', code: '505'},
  {country: 'Niger', code: '227'},
  {country: 'Nigeria', code: '234'},
  {country: 'Niue', code: '683'},
  {country: 'Norfolk Island', code: '672'},
  {country: 'Northern Mariana Islands', code: '1670'},
  {country: 'North Korea', code: '850'},
  {country: 'North Macedonia', code: '389'},
  {country: 'Norway', code: '47'},
  {country: 'Oman', code: '968'},
  {country: 'Pakistan', code: '92'},
  {country: 'Palau', code: '680'},
  {country: 'Palestine', code: '970'},
  {country: 'Panama', code: '507'},
  {country: 'Papua New Guinea', code: '675'},
  {country: 'Paraguay', code: '595'},
  {country: 'Peru', code: '51'},
  {country: 'Philippines', code: '63'},
  {country: 'Pitcairn', code: '64'},
  {country: 'Poland', code: '48'},
  {country: 'Portugal', code: '351'},
  {country: 'Puerto Rico', code: '1'},
  {country: 'Qatar', code: '974'},
  {country: 'Réunion', code: '262'},
  {country: 'Romania', code: '40'},
  {country: 'Russia', code: '7'},
  {country: 'Rwanda', code: '250'},
  {country: 'Saint Barthélemy', code: '590'},
  {country: 'Saint Helena', code: '290'},
  {country: 'Saint Kitts and Nevis', code: '1869'},
  {country: 'Saint Lucia', code: '1758'},
  {country: 'Saint Martin', code: '590'},
  {country: 'Saint Pierre and Miquelon', code: '508'},
  {country: 'Saint Vincent and the Grenadines', code: '1784'},
  {country: 'Samoa', code: '685'},
  {country: 'San Marino', code: '378'},
  {country: 'São Tomé and Príncipe', code: '239'},
  {country: 'Saudi Arabia', code: '966'},
  {country: 'Scotland', code: '44'},
  {country: 'Senegal', code: '221'},
  {country: 'Serbia', code: '381'},
  {country: 'Seychelles', code: '248'},
  {country: 'Sierra Leone', code: '232'},
  {country: 'Singapore', code: '65'},
  {country: 'Sint Maarten', code: '1721'},
  {country: 'Slovakia', code: '421'},
  {country: 'Slovenia', code: '386'},
  {country: 'Solomon Islands', code: '677'},
  {country: 'Somalia', code: '252'},
  {country: 'South Africa', code: '27'},
  {country: 'South Korea', code: '82'},
  {country: 'South Sudan', code: '211'},
  {country: 'Spain', code: '34'},
  {country: 'Sri Lanka', code: '94'},
  {country: 'Sudan', code: '249'},
  {country: 'Suriname', code: '597'},
  {country: 'Sweden', code: '46'},
  {country: 'Switzerland', code: '41'},
  {country: 'Syria', code: '963'},
  {country: 'Taiwan', code: '886'},
  {country: 'Tajikistan', code: '992'},
  {country: 'Tanzania', code: '255'},
  {country: 'Thailand', code: '66'},
  {country: 'Timor-Leste', code: '670'},
  {country: 'Togo', code: '228'},
  {country: 'Tokelau', code: '690'},
  {country: 'Tonga', code: '676'},
  {country: 'Trinidad and Tobago', code: '1868'},
  {country: 'Tunisia', code: '216'},
  {country: 'Turkey', code: '90'},
  {country: 'Turkmenistan', code: '993'},
  {country: 'Turks and Caicos Islands', code: '1649'},
  {country: 'Tuvalu', code: '688'},
  {country: 'U.S. Virgin Islands', code: '1340'},
  {country: 'Uganda', code: '256'},
  {country: 'Ukraine', code: '380'},
  {country: 'United Arab Emirates', code: '971'},
  {country: 'United Kingdom', code: '44'},
  {country: 'United States', code: '1'},
  {country: 'Uruguay', code: '598'},
  {country: 'Uzbekistan', code: '998'},
  {country: 'Vanuatu', code: '678'},
  {country: 'Vatican City', code: '379'},
  {country: 'Venezuela', code: '58'},
  {country: 'Vietnam', code: '84'},
  {country: 'Wales', code: '44'},
  {country: 'Wallis and Futuna', code: '681'},
  {country: 'Western Sahara', code: '212'},
  {country: 'Yemen', code: '967'},
  {country: 'Zambia', code: '260'},
  {country: 'Zimbabwe', code: '263'},
];

export const ONBOARDING_STEPS = {
  AGENCY_DETAIL: 'AGENCY_DETAIL',
  SIGNATORY_DETAIL: 'SIGNATORY_DETAIL',
  BANK_INFORMATION: 'BANK_INFORMATION',
  SUBMIT: 'SUBMIT',
};

export const ONBOARDING_CATEGORIES = {
  REAL_ESTATE_AGENCY_DUBAI_BASED: 'Real Estate Agency (Dubai Based)',
  REAL_ESTATE_AGENCY_OTHER_EMIRATES: 'Real Estate Agency (Other Emirates)',
  NON_REAL_ESTATE_COMPANY: 'Non-Real Estate Company',
  FREELANCER: 'Uae Freelancer',
  REAL_ESTATE_AGENCY_INTERNATIONAL: 'Real Estate Agency',
  NON_REAL_ESTATE_COMPANY_INTERNATIONAL: 'Non-Real Estate Company',
  FREELANCER_INTERNATIONAL: 'Freelancer',
};
export const DOCUMENT_TYPE = {
  passportCopy: 'Authorized Signatory passport copy',
  reraCertificate: 'RERA Certificate',
  brokerCard: 'Broker RERA Card',
  registerationCertificate: 'Trade License',
  emiratesIdCopy: 'Emirates ID',
  validTradeLicense: 'Trade License',
  commercialLicense: 'Trade License',
  visaCopy: 'Visa',
  nonVatDisclosure: 'VAT Disclosure',
  vatCertificate: 'VAT Certificate',
  bankLetter: 'Bank Account',
  poaMoa: 'POA or MOA',
  nationalIdNumberpdf: 'National ID',
  BANK_ACCOUNT_DETAILS: 'Bank details valid proof',
  NATIONAL_ID: 'National ID',
  bankAccountStamp: 'Bank details valid proof',
  proofOfPayment: 'Proof of Payment',
};
export const BooleanDropDownData = [
  {
    id: 'Yes',
    key: 'Yes',
    value: 'Yes',
    is_default: false,
  },
  {
    id: 'No',
    key: 'No',
    value: 'No',
    is_default: false,
  },
];

export const tradeLicenseCategoryData = [
  {
    id: 'DED',
    key: 'DED',
    value: 'DED',
    is_default: false,
  },
  {
    id: 'Freezone',
    key: 'Freezone',
    value: 'Freezone',
    is_default: false,
  },
];

export const AGENT_OVERVIEW_DOCUMENTS = {
  'Authorized Signatory passport copy': 'Passport',
  'Emirates ID': 'Emirates ID',
  'Broker RERA Card': 'RERA Broker Card',
};

export const EOI_OVERVIEW_DOCUMENTS = {
  'Authorized Signatory passport copy': 'Passport',
  'National ID': 'National ID',
  'Proof of Payment': 'Proof of Payment',
  'Trade License': 'Trade License',
};

export const PICKERCOUNTRYVALUES = [
  {
    name: 'Afghanistan',
    code: 'AF',
    dial_code: '+93',
    flag: '🇦🇫',
  },
  {
    name: 'Albania',
    code: 'AL',
    dial_code: '+355',
    flag: '🇦🇱',
  },
  {
    name: 'Algeria',
    code: 'DZ',
    dial_code: '+213',
    flag: '🇩🇿',
  },
  {
    name: 'American Samoa',
    code: 'AS',
    dial_code: '+1684',
    flag: '🇦🇸',
  },
  {
    name: 'Andorra',
    code: 'AD',
    dial_code: '+376',
    flag: '🇦🇩',
  },
  {
    name: 'Angola',
    code: 'AO',
    dial_code: '+244',
    flag: '🇦🇴',
  },
  {
    name: 'Anguilla',
    code: 'AI',
    dial_code: '+1264',
    flag: '🇦🇮',
  },
  {
    name: 'Antarctica',
    code: 'AQ',
    dial_code: '+672',
    flag: '🇦🇶',
  },
  {
    name: 'Antigua and Barbuda',
    code: 'AG',
    dial_code: '+1268',
    flag: '🇦🇬',
  },
  {
    name: 'Argentina',
    code: 'AR',
    dial_code: '+54',
    flag: '🇦🇷',
  },
  {
    name: 'Armenia',
    code: 'AM',
    dial_code: '+374',
    flag: '🇦🇲',
  },
  {
    name: 'Aruba',
    code: 'AW',
    dial_code: '+297',
    flag: '🇦🇼',
  },
  {
    name: 'Australia',
    code: 'AU',
    dial_code: '+61',
    flag: '🇦🇺',
  },
  {
    name: 'Austria',
    code: 'AT',
    dial_code: '+43',
    flag: '🇦🇹',
  },
  {
    name: 'Azerbaijan',
    code: 'AZ',
    dial_code: '+994',
    flag: '🇦🇿',
  },
  {
    name: 'Bahamas',
    code: 'BS',
    dial_code: '+1242',
    flag: '🇧🇸',
  },
  {
    name: 'Bahrain',
    code: 'BH',
    dial_code: '+973',
    flag: '🇧🇭',
  },
  {
    name: 'Bangladesh',
    code: 'BD',
    dial_code: '+880',
    flag: '🇧🇩',
  },
  {
    name: 'Barbados',
    code: 'BB',
    dial_code: '+1246',
    flag: '🇧🇧',
  },
  {
    name: 'Belarus',
    code: 'BY',
    dial_code: '+375',
    flag: '🇧🇾',
  },
  {
    name: 'Belgium',
    code: 'BE',
    dial_code: '+32',
    flag: '🇧🇪',
  },
  {
    name: 'Belize',
    code: 'BZ',
    dial_code: '+501',
    flag: '🇧🇿',
  },
  {
    name: 'Benin',
    code: 'BJ',
    dial_code: '+229',
    flag: '🇧🇯',
  },
  {
    name: 'Bermuda',
    code: 'BM',
    dial_code: '+1441',
    flag: '🇧🇲',
  },
  {
    name: 'Bhutan',
    code: 'BT',
    dial_code: '+975',
    flag: '🇧🇹',
  },
  {
    name: 'Bolivia',
    code: 'BO',
    dial_code: '+591',
    flag: '🇧🇴',
  },
  {
    name: 'Bosnia and Herzegovina',
    code: 'BA',
    dial_code: '+387',
    flag: '🇧🇦',
  },
  {
    name: 'Botswana',
    code: 'BW',
    dial_code: '+267',
    flag: '🇧🇼',
  },
  {
    name: 'Brazil',
    code: 'BR',
    dial_code: '+55',
    flag: '🇧🇷',
  },
  {
    name: 'British Indian Ocean Territory',
    code: 'IO',
    dial_code: '+246',
    flag: '🇮🇴',
  },
  {
    name: 'Brunei Darussalam',
    code: 'BN',
    dial_code: '+673',
    flag: '🇧🇳',
  },
  {
    name: 'Bulgaria',
    code: 'BG',
    dial_code: '+359',
    flag: '🇧🇬',
  },
  {
    name: 'Burkina Faso',
    code: 'BF',
    dial_code: '+226',
    flag: '🇧🇫',
  },
  {
    name: 'Burundi',
    code: 'BI',
    dial_code: '+257',
    flag: '🇧🇮',
  },
  {
    name: 'Cambodia',
    code: 'KH',
    dial_code: '+855',
    flag: '🇰🇭',
  },
  {
    name: 'Cameroon',
    code: 'CM',
    dial_code: '+237',
    flag: '🇨🇲',
  },
  {
    name: 'Canada',
    code: 'CA',
    dial_code: '+1',
    flag: '🇨🇦',
  },
  {
    name: 'Cape Verde',
    code: 'CV',
    dial_code: '+238',
    flag: '🇨🇻',
  },
  {
    name: 'Cayman Islands',
    code: 'KY',
    dial_code: '+345',
    flag: '🇰🇾',
  },
  {
    name: 'Central African Republic',
    code: 'CF',
    dial_code: '+236',
    flag: '🇨🇫',
  },
  {
    name: 'Chad',
    code: 'TD',
    dial_code: '+235',
    flag: '🇹🇩',
  },
  {
    name: 'Chile',
    code: 'CL',
    dial_code: '+56',
    flag: '🇨🇱',
  },
  {
    name: 'China',
    code: 'CN',
    dial_code: '+86',
    flag: '🇨🇳',
  },
  {
    name: 'Christmas Island',
    code: 'CX',
    dial_code: '+61',
    flag: '🇨🇽',
  },
  {
    name: 'Cocos (Keeling) Islands',
    code: 'CC',
    dial_code: '+61',
    flag: '🇨🇨',
  },
  {
    name: 'Colombia',
    code: 'CO',
    dial_code: '+57',
    flag: '🇨🇴',
  },
  {
    name: 'Comoros',
    code: 'KM',
    dial_code: '+269',
    flag: '🇰🇲',
  },
  {
    name: 'Congo',
    code: 'CG',
    dial_code: '+242',
    flag: '🇨🇬',
  },
  {
    name: 'Congo, The Democratic Republic of the',
    code: 'CD',
    dial_code: '+243',
    flag: '🇨🇩',
  },
  {
    name: 'Cook Islands',
    code: 'CK',
    dial_code: '+682',
    flag: '🇨🇰',
  },
  {
    name: 'Costa Rica',
    code: 'CR',
    dial_code: '+506',
    flag: '🇨🇷',
  },
  {
    name: "Cote d'Ivoire",
    code: 'CI',
    dial_code: '+225',
    flag: '🇨🇮',
  },
  {
    name: 'Croatia',
    code: 'HR',
    dial_code: '+385',
    flag: '🇭🇷',
  },
  {
    name: 'Cuba',
    code: 'CU',
    dial_code: '+53',
    flag: '🇨🇺',
  },
  {
    name: 'Cyprus',
    code: 'CY',
    dial_code: '+357',
    flag: '🇨🇾',
  },
  {
    name: 'Czech Republic',
    code: 'CZ',
    dial_code: '+420',
    flag: '🇨🇿',
  },
  {
    name: 'Denmark',
    code: 'DK',
    dial_code: '+45',
    flag: '🇩🇰',
  },
  {
    name: 'Djibouti',
    code: 'DJ',
    dial_code: '+253',
    flag: '🇩🇯',
  },
  {
    name: 'Dominica',
    code: 'DM',
    dial_code: '+1767',
    flag: '🇩🇲',
  },
  {
    name: 'Dominican Republic',
    code: 'DO',
    dial_code: '+1849',
    flag: '🇩🇴',
  },
  {
    name: 'Ecuador',
    code: 'EC',
    dial_code: '+593',
    flag: '🇪🇨',
  },
  {
    name: 'Egypt',
    code: 'EG',
    dial_code: '+20',
    flag: '🇪🇬',
  },
  {
    name: 'El Salvador',
    code: 'SV',
    dial_code: '+503',
    flag: '🇸🇻',
  },
  {
    name: 'Equatorial Guinea',
    code: 'GQ',
    dial_code: '+240',
    flag: '🇬🇶',
  },
  {
    name: 'Eritrea',
    code: 'ER',
    dial_code: '+291',
    flag: '🇪🇷',
  },
  {
    name: 'Estonia',
    code: 'EE',
    dial_code: '+372',
    flag: '🇪🇪',
  },
  {
    name: 'Ethiopia',
    code: 'ET',
    dial_code: '+251',
    flag: '🇪🇹',
  },
  {
    name: 'Falkland Islands (Malvinas)',
    code: 'FK',
    dial_code: '+500',
    flag: '🇫🇰',
  },
  {
    name: 'Faroe Islands',
    code: 'FO',
    dial_code: '+298',
    flag: '🇫🇴',
  },
  {
    name: 'Fiji',
    code: 'FJ',
    dial_code: '+679',
    flag: '🇫🇯',
  },
  {
    name: 'Finland',
    code: 'FI',
    dial_code: '+358',
    flag: '🇫🇮',
  },
  {
    name: 'France',
    code: 'FR',
    dial_code: '+33',
    flag: '🇫🇷',
  },
  {
    name: 'French Guiana',
    code: 'GF',
    dial_code: '+594',
    flag: '🇬🇫',
  },
  {
    name: 'French Polynesia',
    code: 'PF',
    dial_code: '+689',
    flag: '🇵🇫',
  },
  {
    name: 'Gabon',
    code: 'GA',
    dial_code: '+241',
    flag: '🇬🇦',
  },
  {
    name: 'Gambia',
    code: 'GM',
    dial_code: '+220',
    flag: '🇬🇲',
  },
  {
    name: 'Georgia',
    code: 'GE',
    dial_code: '+995',
    flag: '🇬🇪',
  },
  {
    name: 'Germany',
    code: 'DE',
    dial_code: '+49',
    flag: '🇩🇪',
  },
  {
    name: 'Ghana',
    code: 'GH',
    dial_code: '+233',
    flag: '🇬🇭',
  },
  {
    name: 'Gibraltar',
    code: 'GI',
    dial_code: '+350',
    flag: '🇬🇮',
  },
  {
    name: 'Greece',
    code: 'GR',
    dial_code: '+30',
    flag: '🇬🇷',
  },
  {
    name: 'Greenland',
    code: 'GL',
    dial_code: '+299',
    flag: '🇬🇱',
  },
  {
    name: 'Grenada',
    code: 'GD',
    dial_code: '+1473',
    flag: '🇬🇩',
  },
  {
    name: 'Guadeloupe',
    code: 'GP',
    dial_code: '+590',
    flag: '🇬🇵',
  },
  {
    name: 'Guam',
    code: 'GU',
    dial_code: '+1671',
    flag: '🇬🇺',
  },
  {
    name: 'Guatemala',
    code: 'GT',
    dial_code: '+502',
    flag: '🇬🇹',
  },
  {
    name: 'Guernsey',
    code: 'GG',
    dial_code: '+44',
    flag: '🇬🇬',
  },
  {
    name: 'Guinea',
    code: 'GN',
    dial_code: '+224',
    flag: '🇬🇳',
  },
  {
    name: 'Guinea-Bissau',
    code: 'GW',
    dial_code: '+245',
    flag: '🇬🇼',
  },
  {
    name: 'Guyana',
    code: 'GY',
    dial_code: '+595',
    flag: '🇬🇾',
  },
  {
    name: 'Haiti',
    code: 'HT',
    dial_code: '+509',
    flag: '🇭🇹',
  },
  {
    name: 'Holy See (Vatican City State)',
    code: 'VA',
    dial_code: '+379',
    flag: '🇻🇦',
  },
  {
    name: 'Honduras',
    code: 'HN',
    dial_code: '+504',
    flag: '🇭🇳',
  },
  {
    name: 'Hong Kong',
    code: 'HK',
    dial_code: '+852',
    flag: '🇭🇰',
  },
  {
    name: 'Hungary',
    code: 'HU',
    dial_code: '+36',
    flag: '🇭🇺',
  },
  {
    name: 'Iceland',
    code: 'IS',
    dial_code: '+354',
    flag: '🇮🇸',
  },
  {
    name: 'India',
    code: 'IN',
    dial_code: '+91',
    flag: '🇮🇳',
  },
  {
    name: 'Indonesia',
    code: 'ID',
    dial_code: '+62',
    flag: '🇮🇩',
  },
  {
    name: 'Iran, Islamic Republic of',
    code: 'IR',
    dial_code: '+98',
    flag: '🇮🇷',
  },
  {
    name: 'Iraq',
    code: 'IQ',
    dial_code: '+964',
    flag: '🇮🇶',
  },
  {
    name: 'Ireland',
    code: 'IE',
    dial_code: '+353',
    flag: '🇮🇪',
  },
  {
    name: 'Isle of Man',
    code: 'IM',
    dial_code: '+44',
    flag: '🇮🇲',
  },
  {
    name: 'Israel',
    code: 'IL',
    dial_code: '+972',
    flag: '🇮🇱',
  },
  {
    name: 'Italy',
    code: 'IT',
    dial_code: '+39',
    flag: '🇮🇹',
  },
  {
    name: 'Jamaica',
    code: 'JM',
    dial_code: '+1876',
    flag: '🇯🇲',
  },
  {
    name: 'Japan',
    code: 'JP',
    dial_code: '+81',
    flag: '🇯🇵',
  },
  {
    name: 'Jersey',
    code: 'JE',
    dial_code: '+44',
    flag: '🇯🇪',
  },
  {
    name: 'Jordan',
    code: 'JO',
    dial_code: '+962',
    flag: '🇯🇴',
  },
  {
    name: 'Kazakhstan',
    code: 'KZ',
    dial_code: '+77',
    flag: '🇰🇿',
  },
  {
    name: 'Kenya',
    code: 'KE',
    dial_code: '+254',
    flag: '🇰🇪',
  },
  {
    name: 'Kiribati',
    code: 'KI',
    dial_code: '+686',
    flag: '🇰🇮',
  },
  {
    name: "Korea, Democratic People's Republic of",
    code: 'KP',
    dial_code: '+850',
    flag: '🇰🇵',
  },
  {
    name: 'Korea, Republic of',
    code: 'KR',
    dial_code: '+82',
    flag: '🇰🇷',
  },
  {
    name: 'Kuwait',
    code: 'KW',
    dial_code: '+965',
    flag: '🇰🇼',
  },
  {
    name: 'Kyrgyzstan',
    code: 'KG',
    dial_code: '+996',
    flag: '🇰🇬',
  },
  {
    name: "Lao People's Democratic Republic",
    code: 'LA',
    dial_code: '+856',
    flag: '🇱🇦',
  },
  {
    name: 'Latvia',
    code: 'LV',
    dial_code: '+371',
    flag: '🇱🇻',
  },
  {
    name: 'Lebanon',
    code: 'LB',
    dial_code: '+961',
    flag: '🇱🇧',
  },
  {
    name: 'Lesotho',
    code: 'LS',
    dial_code: '+266',
    flag: '🇱🇸',
  },
  {
    name: 'Liberia',
    code: 'LR',
    dial_code: '+231',
    flag: '🇱🇷',
  },
  {
    name: 'Libyan Arab Jamahiriya',
    code: 'LY',
    dial_code: '+218',
    flag: '🇱🇾',
  },
  {
    name: 'Liechtenstein',
    code: 'LI',
    dial_code: '+423',
    flag: '🇱🇮',
  },
  {
    name: 'Lithuania',
    code: 'LT',
    dial_code: '+370',
    flag: '🇱🇹',
  },
  {
    name: 'Luxembourg',
    code: 'LU',
    dial_code: '+352',
    flag: '🇱🇺',
  },
  {
    name: 'Macao',
    code: 'MO',
    dial_code: '+853',
    flag: '🇲🇴',
  },
  {
    name: 'Macedonia, The Former Yugoslav Republic of',
    code: 'MK',
    dial_code: '+389',
    flag: '🇲🇰',
  },
  {
    name: 'Madagascar',
    code: 'MG',
    dial_code: '+261',
    flag: '🇲🇬',
  },
  {
    name: 'Malawi',
    code: 'MW',
    dial_code: '+265',
    flag: '🇲🇼',
  },
  {
    name: 'Malaysia',
    code: 'MY',
    dial_code: '+60',
    flag: '🇲🇾',
  },
  {
    name: 'Maldives',
    code: 'MV',
    dial_code: '+960',
    flag: '🇲🇻',
  },
  {
    name: 'Mali',
    code: 'ML',
    dial_code: '+223',
    flag: '🇲🇱',
  },
  {
    name: 'Malta',
    code: 'MT',
    dial_code: '+356',
    flag: '🇲🇹',
  },
  {
    name: 'Marshall Islands',
    code: 'MH',
    dial_code: '+692',
    flag: '🇲🇭',
  },
  {
    name: 'Martinique',
    code: 'MQ',
    dial_code: '+596',
    flag: '🇲🇶',
  },
  {
    name: 'Mauritania',
    code: 'MR',
    dial_code: '+222',
    flag: '🇲🇷',
  },
  {
    name: 'Mauritius',
    code: 'MU',
    dial_code: '+230',
    flag: '🇲🇺',
  },
  {
    name: 'Mayotte',
    code: 'YT',
    dial_code: '+262',
    flag: '🇾🇹',
  },
  {
    name: 'Mexico',
    code: 'MX',
    dial_code: '+52',
    flag: '🇲🇽',
  },
  {
    name: 'Micronesia, Federated States of',
    code: 'FM',
    dial_code: '+691',
    flag: '🇫🇲',
  },
  {
    name: 'Moldova, Republic of',
    code: 'MD',
    dial_code: '+373',
    flag: '🇲🇩',
  },
  {
    name: 'Monaco',
    code: 'MC',
    dial_code: '+377',
    flag: '🇲🇨',
  },
  {
    name: 'Mongolia',
    code: 'MN',
    dial_code: '+976',
    flag: '🇲🇳',
  },
  {
    name: 'Montenegro',
    code: 'ME',
    dial_code: '+382',
    flag: '🇲🇪',
  },
  {
    name: 'Montserrat',
    code: 'MS',
    dial_code: '+1664',
    flag: '🇲🇸',
  },
  {
    name: 'Morocco',
    code: 'MA',
    dial_code: '+212',
    flag: '🇲🇦',
  },
  {
    name: 'Mozambique',
    code: 'MZ',
    dial_code: '+258',
    flag: '🇲🇿',
  },
  {
    name: 'Myanmar',
    code: 'MM',
    dial_code: '+95',
    flag: '🇲🇲',
  },
  {
    name: 'Namibia',
    code: 'NA',
    dial_code: '+264',
    flag: '🇳🇦',
  },
  {
    name: 'Nauru',
    code: 'NR',
    dial_code: '+674',
    flag: '🇳🇷',
  },
  {
    name: 'Nepal',
    code: 'NP',
    dial_code: '+977',
    flag: '🇳🇵',
  },
  {
    name: 'Netherlands',
    code: 'NL',
    dial_code: '+31',
    flag: '🇳🇱',
  },
  {
    name: 'Netherlands Antilles',
    code: 'AN',
    dial_code: '+599',
    flag: '🇦🇳',
  },
  {
    name: 'New Caledonia',
    code: 'NC',
    dial_code: '+687',
    flag: '🇳🇨',
  },
  {
    name: 'New Zealand',
    code: 'NZ',
    dial_code: '+64',
    flag: '🇳🇿',
  },
  {
    name: 'Nicaragua',
    code: 'NI',
    dial_code: '+505',
    flag: '🇳🇮',
  },
  {
    name: 'Niger',
    code: 'NE',
    dial_code: '+227',
    flag: '🇳🇪',
  },
  {
    name: 'Nigeria',
    code: 'NG',
    dial_code: '+234',
    flag: '🇳🇬',
  },
  {
    name: 'Niue',
    code: 'NU',
    dial_code: '+683',
    flag: '🇳🇺',
  },
  {
    name: 'Norfolk Island',
    code: 'NF',
    dial_code: '+672',
    flag: '🇳🇫',
  },
  {
    name: 'Northern Mariana Islands',
    code: 'MP',
    dial_code: '+1670',
    flag: '🇲🇵',
  },
  {
    name: 'Norway',
    code: 'NO',
    dial_code: '+47',
    flag: '🇳🇴',
  },
  {
    name: 'Oman',
    code: 'OM',
    dial_code: '+968',
    flag: '🇴🇲',
  },
  {
    name: 'Pakistan',
    code: 'PK',
    dial_code: '+92',
    flag: '🇵🇰',
  },
  {
    name: 'Palau',
    code: 'PW',
    dial_code: '+680',
    flag: '🇵🇼',
  },
  {
    name: 'Palestinian Territory, Occupied',
    code: 'PS',
    dial_code: '+970',
    flag: '🇵🇸',
  },
  {
    name: 'Panama',
    code: 'PA',
    dial_code: '+507',
    flag: '🇵🇦',
  },
  {
    name: 'Papua New Guinea',
    code: 'PG',
    dial_code: '+675',
    flag: '🇵🇬',
  },
  {
    name: 'Paraguay',
    code: 'PY',
    dial_code: '+595',
    flag: '🇵🇾',
  },
  {
    name: 'Peru',
    code: 'PE',
    dial_code: '+51',
    flag: '🇵🇪',
  },
  {
    name: 'Philippines',
    code: 'PH',
    dial_code: '+63',
    flag: '🇵🇭',
  },
  {
    name: 'Pitcairn',
    code: 'PN',
    dial_code: '+872',
    flag: '🇵🇳',
  },
  {
    name: 'Poland',
    code: 'PL',
    dial_code: '+48',
    flag: '🇵🇱',
  },
  {
    name: 'Portugal',
    code: 'PT',
    dial_code: '+351',
    flag: '🇵🇹',
  },
  {
    name: 'Puerto Rico',
    code: 'PR',
    dial_code: '+1939',
    flag: '🇵🇷',
  },
  {
    name: 'Qatar',
    code: 'QA',
    dial_code: '+974',
    flag: '🇶🇦',
  },
  {
    name: 'Romania',
    code: 'RO',
    dial_code: '+40',
    flag: '🇷🇴',
  },
  {
    name: 'Russia',
    code: 'RU',
    dial_code: '+7',
    flag: '🇷🇺',
  },
  {
    name: 'Rwanda',
    code: 'RW',
    dial_code: '+250',
    flag: '🇷🇼',
  },
  {
    name: 'Réunion',
    code: 'RE',
    dial_code: '+262',
    flag: '🇷🇪',
  },
  {
    name: 'Saint Barthélemy',
    code: 'BL',
    dial_code: '+590',
    flag: '🇧🇱',
  },
  {
    name: 'Saint Helena, Ascension and Tristan Da Cunha',
    code: 'SH',
    dial_code: '+290',
    flag: '🇸🇭',
  },
  {
    name: 'Saint Kitts and Nevis',
    code: 'KN',
    dial_code: '+1869',
    flag: '🇰🇳',
  },
  {
    name: 'Saint Lucia',
    code: 'LC',
    dial_code: '+1758',
    flag: '🇱🇨',
  },
  {
    name: 'Saint Martin',
    code: 'SX',
    dial_code: '+1721',
    flag: '🇸🇽',
  },
  {
    name: 'Saint Martin',
    code: 'MF',
    dial_code: '+590',
    flag: '🇲🇫',
  },
  {
    name: 'Saint Pierre and Miquelon',
    code: 'PM',
    dial_code: '+508',
    flag: '🇵🇲',
  },
  {
    name: 'Saint Vincent and the Grenadines',
    code: 'VC',
    dial_code: '+1784',
    flag: '🇻🇨',
  },
  {
    name: 'Samoa',
    code: 'WS',
    dial_code: '+685',
    flag: '🇼🇸',
  },
  {
    name: 'San Marino',
    code: 'SM',
    dial_code: '+378',
    flag: '🇸🇲',
  },
  {
    name: 'Sao Tome and Principe',
    code: 'ST',
    dial_code: '+239',
    flag: '🇸🇹',
  },
  {
    name: 'Saudi Arabia',
    code: 'SA',
    dial_code: '+966',
    flag: '🇸🇦',
  },
  {
    name: 'Senegal',
    code: 'SN',
    dial_code: '+221',
    flag: '🇸🇳',
  },
  {
    name: 'Serbia',
    code: 'RS',
    dial_code: '+381',
    flag: '🇷🇸',
  },
  {
    name: 'Seychelles',
    code: 'SC',
    dial_code: '+248',
    flag: '🇸🇨',
  },
  {
    name: 'Sierra Leone',
    code: 'SL',
    dial_code: '+232',
    flag: '🇸🇱',
  },
  {
    name: 'Singapore',
    code: 'SG',
    dial_code: '+65',
    flag: '🇸🇬',
  },
  {
    name: 'Slovakia',
    code: 'SK',
    dial_code: '+421',
    flag: '🇸🇰',
  },
  {
    name: 'Slovenia',
    code: 'SI',
    dial_code: '+386',
    flag: '🇸🇮',
  },
  {
    name: 'Solomon Islands',
    code: 'SB',
    dial_code: '+677',
    flag: '🇸🇧',
  },
  {
    name: 'Somalia',
    code: 'SO',
    dial_code: '+252',
    flag: '🇸🇴',
  },
  {
    name: 'South Africa',
    code: 'ZA',
    dial_code: '+27',
    flag: '🇿🇦',
  },
  {
    name: 'South Georgia and the South Sandwich Islands',
    code: 'GS',
    dial_code: '+500',
    flag: '🇬🇸',
  },
  {
    name: 'Spain',
    code: 'ES',
    dial_code: '+34',
    flag: '🇪🇸',
  },
  {
    name: 'Sri Lanka',
    code: 'LK',
    dial_code: '+94',
    flag: '🇱🇰',
  },
  {
    name: 'Sudan',
    code: 'SD',
    dial_code: '+249',
    flag: '🇸🇩',
  },
  {
    name: 'Suriname',
    code: 'SR',
    dial_code: '+597',
    flag: '🇸🇷',
  },
  {
    name: 'Svalbard and Jan Mayen',
    code: 'SJ',
    dial_code: '+47',
    flag: '🇸🇯',
  },
  {
    name: 'Swaziland',
    code: 'SZ',
    dial_code: '+268',
    flag: '🇸🇿',
  },
  {
    name: 'Sweden',
    code: 'SE',
    dial_code: '+46',
    flag: '🇸🇪',
  },
  {
    name: 'Switzerland',
    code: 'CH',
    dial_code: '+41',
    flag: '🇨🇭',
  },
  {
    name: 'Syrian Arab Republic',
    code: 'SY',
    dial_code: '+963',
    flag: '🇸🇾',
  },
  {
    name: 'Taiwan, Province of China',
    code: 'TW',
    dial_code: '+886',
    flag: '🇹🇼',
  },
  {
    name: 'Tajikistan',
    code: 'TJ',
    dial_code: '+992',
    flag: '🇹🇯',
  },
  {
    name: 'Tanzania, United Republic of',
    code: 'TZ',
    dial_code: '+255',
    flag: '🇹🇿',
  },
  {
    name: 'Thailand',
    code: 'TH',
    dial_code: '+66',
    flag: '🇹🇭',
  },
  {
    name: 'Timor-Leste',
    code: 'TL',
    dial_code: '+670',
    flag: '🇹🇱',
  },
  {
    name: 'Togo',
    code: 'TG',
    dial_code: '+228',
    flag: '🇹🇬',
  },
  {
    name: 'Tokelau',
    code: 'TK',
    dial_code: '+690',
    flag: '🇹🇰',
  },
  {
    name: 'Tonga',
    code: 'TO',
    dial_code: '+676',
    flag: '🇹🇴',
  },
  {
    name: 'Trinidad and Tobago',
    code: 'TT',
    dial_code: '+1868',
    flag: '🇹🇹',
  },
  {
    name: 'Tunisia',
    code: 'TN',
    dial_code: '+216',
    flag: '🇹🇳',
  },
  {
    name: 'Turkey',
    code: 'TR',
    dial_code: '+90',
    flag: '🇹🇷',
  },
  {
    name: 'Turkmenistan',
    code: 'TM',
    dial_code: '+993',
    flag: '🇹🇲',
  },
  {
    name: 'Turks and Caicos Islands',
    code: 'TC',
    dial_code: '+1649',
    flag: '🇹🇨',
  },
  {
    name: 'Tuvalu',
    code: 'TV',
    dial_code: '+688',
    flag: '🇹🇻',
  },
  {
    name: 'Uganda',
    code: 'UG',
    dial_code: '+256',
    flag: '🇺🇬',
  },
  {
    name: 'Ukraine',
    code: 'UA',
    dial_code: '+380',
    flag: '🇺🇦',
  },
  {
    name: 'United Arab Emirates',
    code: 'AE',
    dial_code: '+971',
    flag: '🇦🇪',
  },
  {
    name: 'United Kingdom',
    code: 'GB',
    dial_code: '+44',
    flag: '🇬🇧',
  },
  {
    name: 'United States',
    code: 'US',
    dial_code: '+1',
    flag: '🇺🇸',
  },
  {
    name: 'Uruguay',
    code: 'UY',
    dial_code: '+598',
    flag: '🇺🇾',
  },
  {
    name: 'Uzbekistan',
    code: 'UZ',
    dial_code: '+998',
    flag: '🇺🇿',
  },
  {
    name: 'Vanuatu',
    code: 'VU',
    dial_code: '+678',
    flag: '🇻🇺',
  },
  {
    name: 'Venezuela, Bolivarian Republic of',
    code: 'VE',
    dial_code: '+58',
    flag: '🇻🇪',
  },
  {
    name: 'Viet Nam',
    code: 'VN',
    dial_code: '+84',
    flag: '🇻🇳',
  },
  {
    name: 'Virgin Islands, British',
    code: 'VG',
    dial_code: '+1284',
    flag: '🇻🇬',
  },
  {
    name: 'Virgin Islands, U.S.',
    code: 'VI',
    dial_code: '+1340',
    flag: '🇻🇮',
  },
  {
    name: 'Wallis and Futuna',
    code: 'WF',
    dial_code: '+681',
    flag: '🇼🇫',
  },
  {
    name: 'Yemen',
    code: 'YE',
    dial_code: '+967',
    flag: '🇾🇪',
  },
  {
    name: 'Zambia',
    code: 'ZM',
    dial_code: '+260',
    flag: '🇿🇲',
  },
  {
    name: 'Zimbabwe',
    code: 'ZW',
    dial_code: '+263',
    flag: '🇿🇼',
  },
  {
    name: 'Åland Islands',
    code: 'AX',
    dial_code: '+358',
    flag: '🇦🇽',
  },
];
